### ISSUE TITLE
[Bug]: Failed to load log: TypeError: fetch failed while first login to scalr extension

### ISSUE THREAD

**Issue by lonesurvivor84** [Scalr/scalr-vscode#27]
**Describe the bug**
When trying to login to the scalr VS code, the following message appears: 
Failed to load log: TypeError: fetch failed

**To Reproduce**

1. Download VScode Scalr extension.
2. Scalr Extension -> Login
3. Input values for Account.
4. Put in either existing PAT or generate a new PAT.
5. Error Appears on VS Code:
`Failed to load log: TypeError: fetch failed`

**Expected behavior**
Expecting to Login.

**Screenshots**
![image](https://github.com/user-attachments/assets/ad8333fe-5086-477a-ade1-887da1155fa9)
![image](https://github.com/user-attachments/assets/5d669b36-a989-4dc8-ae17-8b804fa6e257)

**Extension Version (please complete the following information):**
-   Version: v0.0.3

**VSCode Version:**
Version: 1.93.0 (system setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0

**OS:**
-   OS: Windows_NT x64 10.0.22631

**Additional context**

**Comment by penja** [comment]
@lonesurvivor84 Thank you for the report. I suspect there may be issues with the API permissions required by VS Code. I’ve reduced some API calls and added better error handling. Please try again with the next release.

**Comment by emocharnik** [comment]
Hi, @lonesurvivor84. Thanks for the report, the new version **0.0.4** with a fix is released. Please update your extension and try to login again.

**Comment by lonesurvivor84** [comment]
Hi @emocharnik , unfortunately still an issue with v0.0.4.
![image](https://github.com/user-attachments/assets/8b8d4a2a-065f-4de3-93ef-2dd0cc7d28a4)

**Comment by penja** [comment]
@lonesurvivor84 Thank you for the report. I've reopened the issue for investigating.

**Comment by penja** [comment]
@lonesurvivor84  Could you share the name of the account that you tried to log in?

**Comment by emocharnik** [comment]
@lonesurvivor84 can we have a live session to troubleshoot your issue? If so, please open a request at https://support.scalr.com with an email and I'll send you an invite in the Google Calendar.

**Comment by emocharnik** [comment]
@lonesurvivor84 do you have a chance to troubleshoot the issue?
